apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
spec:
  selector:
    app: {{ .Release.Name }}-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: mongodb
  type: ClusterIP